---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Re-configure yum repositories for CentOS 7 and 8 to point to vault
      become: true
      when:
        - (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8') or
          (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')
      block:
        - name: Disable default CentOS mirrors (backup original)
          ansible.builtin.lineinfile:
            path: /etc/yum.repos.d/CentOS-*
            regexp: '^mirrorlist'
            replace: '#mirrorlist'
            backup: yes

        - name: Update CentOS mirrors to vault.centos.org (backup original)
          ansible.builtin.lineinfile:
            path: /etc/yum.repos.d/CentOS-*
            regexp: '^baseurl=http://mirror.centos.org'
            replace: 'baseurl=http://vault.centos.org'
            backup: yes

    - name: Install Fedora EPEL repo
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Update APT cache
      ansible.builtin.package:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Git
      ansible.builtin.package: name=git state=present

    - name: Install Python compile dependencies
      ansible.builtin.yum:
        name:
          - bzip2-devel
          - gcc
          - make
          - openssl-devel
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install Python compile dependencies
      ansible.builtin.package:
        name:
          - libbz2-dev
          - gcc
          - make
          - libssl-dev
          - wget
          - zlib1g-dev
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
