---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install EPEL for CentOS 9
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '9'
      become: true

    - name: Update APT cache
      ansible.builtin.package:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Git
      ansible.builtin.package: name=git state=present

    - name: Install Python compile dependencies
      ansible.builtin.yum:
        name:
          - bzip2-devel
          - gcc
          - make
          - openssl-devel
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install Python compile dependencies
      ansible.builtin.package:
        name:
          - libbz2-dev
          - gcc
          - make
          - libssl-dev
          - wget
          - zlib1g-dev
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
