---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Fedora EPEL repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Git
      package: name=git state=present

    - name: Install Python compile dependencies
      yum:
        name:
          - bzip2-devel
          - gcc
          - make
          - openssl-devel
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install Python compile dependencies
      apt:
        name:
          - libbz2-dev
          - gcc
          - make
          - libssl-dev
          - wget
          - zlib1g-dev
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
